### ISSUE TITLE
Unexpected Failure

### ISSUE THREAD

**Issue by connect2karthik** [UberEther/standalone-docker-sailpoint-iiq#1]
![Unexpected Failure](https://user-images.githubusercontent.com/61401605/75254877-0d565b00-5807-11ea-8deb-c2c84c5e5d06.png)

I have followed the notes and build was successful. But facing above error while executing bootstrap.sh script. Please advise.

**Comment by nbhansali** [comment]
Following the notes and I was able to build successful but running into the error below:

![Screen Shot 2020-03-13 at 10 53 02 AM](https://user-images.githubusercontent.com/2665470/76631929-d24b6b80-6518-11ea-9770-46d2bc0b33b2.png)

**Comment by qontro1** [comment]
> ![Unexpected Failure](https://user-images.githubusercontent.com/61401605/75254877-0d565b00-5807-11ea-8deb-c2c84c5e5d06.png)
> 
> I have followed the notes and build was successful. But facing above error while executing bootstrap.sh script. Please advise.

Also experiencing the same problem - the database container will constantly crashes on running - any advice?

**Comment by andrew-cachiaras** [comment]
> Following the notes and I was able to build successful but running into the error below:
> 
> ![Screen Shot 2020-03-13 at 10 53 02 AM](https://user-images.githubusercontent.com/2665470/76631929-d24b6b80-6518-11ea-9770-46d2bc0b33b2.png)

Were you able to resolve this? I am running into the same issue.

**Comment by topperge** [comment]
My apologies everyone, for some reason this issue didn't come through to us. We'll take a look at it next week.

**Comment by topperge** [comment]
#2 Updates made to work with the latest versions of IIQ and SSB. Should be good to go. Please let us know if there are any other issues.
