### ISSUE TITLE
missing ant-contrib-1.0b3.jar

### ISSUE THREAD

**Issue by iamtaosong** [UberEther/standalone-docker-sailpoint-iiq#3]
the initial build failed because of missing build-lib/ant-contrib-1.0b3.jar.
build.xml expecting the jar 
    
    <property name="ue.lib.antcontrib" location="build-lib/ant-contrib-1.0b3.jar" />

    
    <taskdef resource="net/sf/antcontrib/antlib.xml" classpath="${ue.lib.antcontrib}" />

**Comment by NSammut** [comment]
Thanks for letting us know! We should have that fixed here soon.
