### ISSUE TITLE
Image showing SailPoint IdentityIQ Docker CI/CD Process in README.md is Missing

### ISSUE THREAD

**Issue by ErinsMatthew** [UberEther/standalone-docker-sailpoint-iiq#9]
The missing showing SailPoint IdentityIQ Docker CI/CD Process in README.md is missing.  It points to a link on GitHub that returns "Not Found".

https://camo.githubusercontent.com/03a0962217646e1da6261c4ff1c1deba3d8400a027a2ce735fa8f37d74adfa0a/68747470733a2f2f7562657265746865722e636f6d2f696d616765732f536c696465342e706e67 is where mine links to.

<img width="432" alt="Screen Shot 2021-04-18 at 08 25 39" src="https://user-images.githubusercontent.com/921561/115147273-dac97c00-a01f-11eb-8411-ab185576bf97.png">

**Comment by NSammut** [comment]
Thanks for lettings us know! We made some big changes to our website recently and it looks like the path to the image has changed. We'll get this updated soon.
